### PR TITLE
Ditch the composition

### PR DESCRIPTION
**Pull request by mortonjt**
This popped up when we were reviewing the documentation updates here: https://github.com/qiime2/docs/pull/346

Basically, the newest changes to include the pseudocount as an option into the ilr-transform commands negates the need for a Composition type.

However, we also need to modify all other methods that consume Composition objects, which includes visualizations.

In this PR, we just have some commands updated to accept `FeatureTable[Frequency]` with pseudocount options instead.

### CODE REVIEW

**Comment by mortonjt** [comment]
Sorry @ebolyen , @lisa55asil just recognized this issue when we were doing the documentation

**Comment by ebolyen** [comment]
oh, that makes sense. Does this impact ANCOM?

**Comment by mortonjt** [comment]
Nope, since there is still a add_pseudocount cmd.

But may want to address with ANCOM later - - will have to discuss with
Shyamal

**Comment by mortonjt** [comment]
Ok, we have a default pseudocount of 0.5 now ... 

Now that we are replacing zeros with pseudocounts, it is not great to have a pseudocount default of 1 since that won't distinguish between singletons or zeros.  0.5 will at least distinguish

**Review by ebolyen — APPROVED** [review]

**Pull request merged**
