### PR TITLE
BLD: Adding in qiime2 files

### PR DESCRIPTION
**Pull request by mortonjt**

### CODE REVIEW

**Comment by mortonjt** [comment]
@ebolyen - we have all of the basic components for q2-gneiss here.  And it seems to be working.

How should we proceed from here?

**Comment by ebolyen** [comment]
@mortonjt, awesome! I think at this point we're ready to merge these changes and migrate this repo to the qiime2 org. Once that is done we'll take care of connecting things to our CI system, so you shouldn't need to worry about it too much. We'll probably just make a PR which you can review if you'd like.

**Comment by mortonjt** [comment]
ok! let me double check everything with this [PR](https://github.com/biocore/gneiss/pull/214) first. 
Once we have all of those tests passing and the tutorials reproduced with the new decoupling - I'll merge this PR.

**Comment by mortonjt** [comment]
Look like the tutorials work and all of the tests are passing - so this should be safe to merge.

**Comment by ebolyen** [comment]
:tada:

**Pull request merged**
