### PR TITLE
Core regression

### PR DESCRIPTION
**Pull request by mortonjt**
This adds a high level wrapper for the ols regression, as originally recommended by @nbokulich .  Basically, this performs the pseudocount addition, the ilr transform, and the ols regression given a tree.  This is ideal for scenarios with a pre-defined tree, like a phylogenetic tree.

### CODE REVIEW

**Comment by thermokarst** [comment]
Hi @mortonjt, looks like there are a few different failures happening here (linting, missing data, invalid metadata). Let us know if you need some help fixing this up. Thanks!

**Comment by jairideout** [comment]
Hi @mortonjt! We noticed this PR has been open for awhile -- is this a WIP or can it be closed?

**Comment by mortonjt** [comment]
This should not be closed, because this will provide a means to actually use phylogenetic trees.  The way that the tree types are currently structured, this is not possible.

I'm aiming to have this done by the next release.

**Comment by mortonjt** [comment]
Just raised an issue [here](https://github.com/biocore/gneiss/issues/241) to make sure that I don't forget.  Sorry about the confusion

**Comment by jairideout** [comment]
OK we'll keep this open and ignore for now, just ping us when it's ready for review. For the 2017.10 release cycle we'll need the PR ready for review by 10/19. Thanks!

**Comment by mortonjt** [comment]
Sounds good!  Thanks!

**Comment by mortonjt** [comment]
Sorry for the hold up -- I have tested it, and it seems to be working.

I have explicitly changed the types, and changed the name to 'phylogenetic_regression'.  While it is still using the same core balance ols method, it explicitly takes a phylogenetic tree as input.  This is so that the data handling on the phylogenetic tree (i.e. matching tips, renaming internal nodes) is done within this module and hidden from the user.

This should be ready for review - let me know if there is anything else that needs to be done with this!  I'll be pushing out another tutorial immediately after this is in.

**Comment by mortonjt** [comment]
@jairideout @thermokarst @ebolyen can this still be reviewed to merge into the next release?

**Comment by jairideout** [comment]
Yes!

**Comment by mortonjt** [comment]
Sorry, accidental pushed in another commit from another PR :/

I'm thinking about since there is filtering / renaming in both the table and the tree, that could be useful to be done in `balance-taxonomy`.  I'm going to push in one more PR to enable that functionality.

**Comment by mortonjt** [comment]
I'm going to go ahead and close this and open up a new PR.  This new PR will fix the problem that we have had with phylogenies, while prompting a much simpler solution.

**Pull request closed without merging**
